basedir: "/data_nfs/og86asub/netmap/netmap-evaluation/"
outfolder: "/data_nfs/og86asub/netmap/netmap-evaluation"
image_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/images"
r_script_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/src/data_simulation/R"
network_module_config: "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/network_modules/network_modules.yaml"
number_test_modules: 10
input_network_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/data/input_network"
clustered_network_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/data/clustered_network"
simulated_data_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/data/simulated_data"
perturb_seq_subset_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/data/perturb_seq_subsets"
summary_output_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/results/summaries"

data_simulation_base_configs:
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/data_simulation/config_easy.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/data_simulation/config_noise.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/data_simulation/config_three.yaml"
    #- "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/data_simulation/config_five.yaml"



netmap_base_configs:
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_1.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_2.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_3.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_4.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_5.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_6.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_7.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_8.yaml"
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/netmap/config_9.yaml"




csnet_base_configs:
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/csnet/config.yaml"

scgenerai_base_configs:
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/scgenerai/config.yaml"

grnboost2_base_configs:
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/grnboost2/config.yaml"

perturb_seq_base_configs:
    - "/data_nfs/og86asub/netmap/netmap-evaluation/configurations/perturb_seq/config.yaml"


result_folder: "/data_nfs/og86asub/netmap/netmap-evaluation/results"

netmap_config_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/results/configurations/netmap"
scgenerai_config_dir : "/data_nfs/og86asub/netmap/netmap-evaluation/results/configurations/scgenerai/"
csnet_config_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/results/configurations/csnet/"
grnboost2_config_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/results/configurations/grnboost2/"

simulated_data_config_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/results/configurations/data_simulation"
perturb_seq_config_dir: "/data_nfs/og86asub/netmap/netmap-evaluation/results/configurations/perturb_seq"