input_data: /data_nfs/og86asub/netmap/NetMap_LRP/benchmark/data/simulated_data/config_ro/net_51_5864/data.h5ad
layer: 'X'
transcription_factors: /data_nfs/datasets/SCENIC_DB/tf_lists/allTFs_hg38.txt
tf_only: false
penalize_error: true
adata_filename: grn_lrp.h5ad
grn: grn_lrp.tsv
output_directory: /data_nfs/og86asub/netmap/NetMap_LRP/benchmark/results/base_config/config_ro/net_51_5864
overwrite: true
epochs: 150
learning_rate: 0.005
optimizer: Adam
test_size: 0.3
masking_percentage: 0.1
masking_value: 0
print_every: 100
n_top_edges: 100
n_models: 10
model: negbin
loss_fn: LogCoshLoss
xai_method: GradientShap
percentile: 50
penalty: None
raw_attribution: false
aggregation_strategy: 'sum'
use_differential: false

