input_data: /data_nfs/og86asub/netmap/NetMap_LRP/benchmark/data/simulated_data/config_ro/net_51_5864/data.h5ad
layer: 'X'
transcription_factors: /data_nfs/datasets/SCENIC_DB/tf_lists/allTFs_hg38.txt
tf_only: false
penalize_error: true
adata_filename: grn_lrp.h5ad
grn: grn_lrp.tsv
output_directory: /data_nfs/og86asub/netmap/NetMap_LRP/benchmark/results/base_config/config_ro/net_51_5864
epochs: 10000 # Training uses early stopping
model: NegativeBinomialAutoencoder   #ZINBAutoencoder
n_models: 20
learning_rate: 0.005
optimizer: Adam
validation_size: 0.2
xai_method: GradientShap
masking_percentage: 0.1
aggregation_strategy: 'mean'